version: '2.1'
services:
  tor:
    image: arpitjindal1997/myst-multiarch:tor
    cap_add:
     - NET_ADMIN
     - SYS_MODULE
    sysctls:
     - net.ipv6.conf.all.disable_ipv6=0
     - net.ipv6.conf.all.forwarding=1
    environment:
     - WG_COLOR_MODE=always
     - LOG_LEVEL=info
    ports:
     - 9029:9029/tcp
     - 9030:9030/tcp
    privileged: true
    volumes:
     - ./tor:/var/lib/tor
     - ./torrc:/etc/tor/torrc
    networks:
      app_net:
        ipv6_address: 2001:3200:3100::20
networks:
  app_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:3200:3100::/64
          gateway: 2001:3200:3100::1
